repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: \.png$

  - repo: local
    hooks:
      - id: oelint-adv
        name: OE Lint Advanced
        entry: .github/scripts/oelint-check.sh
        language: python
        additional_dependencies: ['oelint-adv==9.1.4']
        types: [file]
        files: \.(bb|bbappend|bbclass|inc|conf)$
        pass_filenames: true
